### ISSUE TITLE
不支持python3.8

### ISSUE THREAD

**Issue by 3356153957** [OptiJava/hooks#1]
[MCDR] [02:20:38] [TaskExecutor/INFO]: 正在重载插件 hooks@2.1.2
[MCDR] [02:20:38] [TaskExecutor/INFO]: 插件 hooks@2.1.2 已卸载
[MCDR] [02:20:38] [TaskExecutor/INFO]: 插件 hooks@2.1.2 已重载
[MCDR] [02:20:38] [TaskExecutor/ERROR]: Fail to load the entry point of hooks@2.1.2
Traceback (most recent call last):
File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/mcdreforged/plugin/type/multi_file_plugin.py", line 88, in _on_ready
self._load_entry_instance()
File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/mcdreforged/plugin/type/regular_plugin.py", line 66, in _load_entry_instance
self.entry_module_instance = self._import_entrypoint_module()
File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/mcdreforged/plugin/type/multi_file_plugin.py", line 56, in _import_entrypoint_module
mod = importlib.import_module(self.get_metadata().entrypoint)
File "/root/.pyenv/versions/3.8.10/lib/python3.8/importlib/init.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
File "<frozen zipimport>", line 259, in load_module
File "plugins/hooks-v2.1.2.mcdr/hooks/init.py", line 9, in <module>
import hooks.config as cfg
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
File "<frozen zipimport>", line 259, in load_module
File "plugins/hooks-v2.1.2.mcdr/hooks/config.py", line 15, in <module>
class TempConfig:
File "plugins/hooks-v2.1.2.mcdr/hooks/config.py", line 40, in TempConfig
hooks: dict[str, List[str]]
TypeError: 'type' object is not subscriptable

**Comment by OptiJava** [comment]
中考完了之后修（

**Comment by OptiJava** [comment]
可以先试试[这个](https://github.com/OptiJava/hooks/actions/runs/9689619194/artifacts/1642846609)
大概率应该修好了（
